print ("Heollo World")

print ("Heollo World")
print ("Heollo World")
print ("Heollo World")
print ("Heollo World")
print ("Heollo World")
print ("Heollo World")
for x in range(10)
    print(x)
print(x)
print(x)
print(x)
